project_id = "yllrqgwiztnbhpxdnsvi"

[functions.send-feedback-slack]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.process-receipt]
verify_jwt = false

[functions.sync-data]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.check-habit-reminders]
verify_jwt = false
[functions.revenuecat-webhook]
verify_jwt = false
